### ISSUE TITLE
Empty out pending loot for units killed by explosives 

### ISSUE THREAD

**Issue by MalucoMarinero** [X2CommunityCore/X2CommunityHighlander#112]
is this vanilla compatible?

**Comment by BTernaryTau** [comment]
Isn't this just a bugfix for vanilla?

**Comment by MalucoMarinero** [comment]
I think it is actually, I was concerned partial behaviour from LW's corpse destruction mechanics was leaking into the highlander, not 100%, will reread the issue's code when I get a chance

**Comment by robojumper** [comment]
Can safely be considered a bugfix.
