### ISSUE TITLE
Line 784: InteractiveObject.MakeAvailableLoot(NewGameState);

### ISSUE THREAD

**Issue by MalucoMarinero** [X2CommunityCore/X2CommunityHighlander#141]
don't fully understand this added line in TacMissionManager, bug fix or enhancement?

**Comment by robojumper** [comment]
Might be an LW1.3 enhancement re: Smash&Grab mission type. It could be used to create interactive state object loot before the object is actually interacted with, which shouldn't cause any behavioral changes, just the possibility to actually know which items are where -- which could play a role in the mission type.

Adding the enhancement label for now, leaving it open until LW1.3.

**Comment by MalucoMarinero** [comment]
No worries, that does make sense though, we'll wait and see.

**Comment by robojumper** [comment]
Bug fix. Interactive Level actors can contain loot, but if the loot is made available only by the ability, the empty popup will appear as if there wasn't anything looted -- see X2Action_Loot.state'Executing'.Begin:

    `PRES.UIInventoryTactical(OldUnitState, OldLootableObjectState, OnUIInventoryTacticalClosed);
