### ISSUE TITLE
Fix better AI AOE LOS Checks

### ISSUE THREAD

**Issue by bountygiver** [X2CommunityCore/X2CommunityHighlander#163]
In `X2TacticalVisibilityHelpers`, `CanUnitSeeLocation` gets short circuited to true if the sight range is larger than distance so the rest of the actual LOS testing's result (specifically `OutVisInfo.bClearLOS`) is not used, this function is used by AI behaviour tree to check if a target is a valid AOE target.

Fixing this should fix the problem of AIs using aoe abilities on units without LOS

**Comment by robojumper** [comment]
Even though it's probably "just a bugfix", it'll change the game and AI balance enough to really make a difference, so the fix should be gated behind a config option, don't you think?

It doesn't look like the function is used for anything else than AI.

**Comment by bountygiver** [comment]
Since #260 resolved this, I guess we will just add a warning to anyone who want to use `CanUnitSeeLocation` function that it doesn't actually check LOS
