### ISSUE TITLE
LWXComGameVersionTemplate implementation for Community Highlander versioning

### ISSUE THREAD

**Issue by MalucoMarinero** [X2CommunityCore/X2CommunityHighlander#203]
We will likely want to  deploy releases at a greater rate than the LW team, given we're meeting the needs of more modders hopefully.

I'm suggesting we mirror the implementation of LWXComGameVersionTemplate with CHXComGameVersionTemplate (CommunityHighlander) and use those version numbers for our own releases that are independant of the LW release cycle. I'd suggest we use Major and Minor versions semantically, with Major Version representing any backwards incompatible changes (although we'd trried to avoid ever needing to do that), and Minor Version representing additions that more or less assure mods built against earlier minor versions still work.

The theory here is we would ALWAYS increment the CH version every one of our releases, and then the LW version increments whenever we merge in new LW changes from upstream.

Does this seem like a reasonable strategy?

**Comment by BTernaryTau** [comment]
That makes sense to me.

**Comment by robojumper** [comment]
Sounds reasonable.

**Comment by MalucoMarinero** [comment]
Version file created, will be incremented with each new release. Implementation is almost exactly the same as Long War's however we have room for 9999 minor versions rather than 99.
