### ISSUE TITLE
Modify X2Effect target condition checking order to be more consistent with X2AbilityTemplate

### ISSUE THREAD

**Issue by abatewongc** [X2CommunityCore/X2CommunityHighlander#209]
Currently, `X2Effect.ApplyEffect` checks conditions in the following order: `AbilityMeetsCondition` -> `MeetsCondition` -> `MeetsConditionWithSource`.

This is inconsistent with how the native method `X2AbilityTemplate.CheckTargetConditions` (and I'm guessing, the other two methods `CheckShooterConditions` and `CheckMultiTargetConditions`) checks conditions, which does `MeetsCondition` -> `MeetsConditionWithSource` -> `AbilityMeetsCondition`. 

The fix would be a simple cut/paste of the code that calls the methods in order. It shouldn't affect anything because this is already how condition checking works internally.

**Comment by MalucoMarinero** [comment]
@abatewongc  any possible side effects of this change? I guess CheckTargetConditions is only visualisation and control so behaviour (X2Effect.ApplyEffect) should remain untouched and therefore we shouldn't break any vanilla behaviours hopefully

**Comment by abatewongc** [comment]
I doubt it, although it's certainly possible that if there exists a condition that has different behavior based on the order in which its methods are called as a means to determine where it's running, then this change would break it. I'm not aware of anything like that in vanilla, though.

**Comment by robojumper** [comment]
Just looked over the behavior. There is also a check in X2Effect_ApplyWeaponDamage.GetDamagePreview:

	AvailableCode = ConditionIter.AbilityMeetsCondition(AbilityState, TargetUnit);
	if (AvailableCode != 'AA_Success')
		return;
	AvailableCode = ConditionIter.MeetsCondition(TargetUnit);
	if (AvailableCode != 'AA_Success')
		return;
	AvailableCode = ConditionIter.MeetsConditionWithSource(TargetUnit, SourceUnit);
	if (AvailableCode != 'AA_Success')
		return;

It might be more important than it seems, since the AI also checks this damage preview for various things.

Would you consider changing the order there too?
