### ISSUE TITLE
shotwing scrolls will never revert back to top

### ISSUE THREAD

**Issue by eraze93** [X2CommunityCore/X2CommunityHighlander#223]
helo is there any way to fix the ShotWings scrolls (because of too many fields) it does not always properly revert back to the top?
this happen when it try to scroll up then i change to another target OR soldier i have great screenshot:

http://imgur.com/a/YSmb0 
http://imgur.com/a/0GwMl 
http://imgur.com/a/m2M4o

**Comment by robojumper** [comment]
Hello! Are you already using the Community Highlander? That issue is supposed to be fixed with #188.

(Apologies, we need a proper bug report template here.)

**Comment by eraze93** [comment]
yes thats why i post it here. haha. stilll floating up and causing no information at all. black screen.

**Comment by robojumper** [comment]
The mod "Perfect Information" overrides the affected class and causes the fix to not take effect. The author could fix it on their side easily.
