### ISSUE TITLE
Allow overriding of HasAvailablePerksToAssign() output

### ISSUE THREAD

**Issue by BTernaryTau** [X2CommunityCore/X2CommunityHighlander#33]
XComGameState_Unit currently has an exception for Psi Operatives in HasAvailablePerksToAssign() that prevents the player from choosing a perk for every rank a soldier has reached. It would be ideal for mods to be capable of extending this behavior to other classes.

**Comment by BTernaryTau** [comment]
Changing the issue to allowing general changes to the output of HasAvailablePerksToAssign().

**Comment by MalucoMarinero** [comment]
Merged and documented for next release.
