### ISSUE TITLE
Allow usage of HeavyWeapon inventory slot for SoldierClass

### ISSUE THREAD

**Issue by MalucoMarinero** [X2CommunityCore/X2CommunityHighlander#42]
used for LW Technical Class

**Comment by robojumper** [comment]
There's one bit of an issue where no one can equip heavy weapons in vanilla (since it's now restricted). TT has gated that behavior behind a config bool flag now, it might be in 1.3.

**Comment by MalucoMarinero** [comment]
cheers

**Comment by MalucoMarinero** [comment]
@robojumper I've commented out the change as I don't want to 'guess' their config variable or anything, there's no reason we need to carry it for now and it's trivial to merge in once they make their change.

**Comment by robojumper** [comment]
Fixed as of LW1.3.
