### ISSUE TITLE
Add Event Hook for mods to calculate the result of GetNumCiviliansKilled.

### ISSUE THREAD

**Issue by MalucoMarinero** [X2CommunityCore/X2CommunityHighlander#6]
Mods should listen to the event 'GetNumCiviliansKilled' and modify the tuple with this data structure:

Data[0].b = true;
Data[1].i = 5; // number of civilians killed.
Data[2].i = 10; // total number of civilians.

**Comment by BTernaryTau** [comment]
I'm confused here. Doesn't LW2 depend on this hook changing civilians killed and total civilians even without Data[0].b set equal to true?

**Comment by robojumper** [comment]
Yup, @MalucoMarinero, `Tuple.Data[0].b` is just a passed function parameter. Their implementation was fine and your change probably breaks it.

The fact that a mod wants to override it is indicated by `Tuple.Data.Length == 3`.

**Comment by MalucoMarinero** [comment]
I have atoned for my sin, closing this issue once more, #206 to talk about the new hooks.
